### ISSUE TITLE
add example of outlines for the off-curve

### ISSUE THREAD

**Issue by PeterCon** [arrowtype/NLI-test#1]
Thanks for writing this up!

>Adust Source B to make the output look correct as the halfway point between A & C. Notably, Source B won’t look like the 50% shape – remember, this draw is just to set offcurves for interpolation paths, so it will be distorted by a little or a lot.

It would be helpful if you added an example showing what source B ends up looking like in some particular cases; e.g., for the rotation of the rectangle, or the opening of "c".

**Comment by arrowtype** [comment]
Good suggestion, thanks! I may pick this up again in the future, and use that suggestion if so. For now, though, I’ve decided to take a step back from this area (see updated Readme for details).
